[project]
name = "data-pipeline"
version = "0.1.0"
description = "Financial data pipeline for stocks analytics platform"
authors = [
    {name = "Víctor Román", email = "v.roman.aragay@hotmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    # Data fetching
    "yfinance>=0.2.18",
    "requests>=2.31.0",
    
    # Data processing
    "pandas>=2.1.0",
    "pyarrow>=13.0.0",  # For Parquet support
    "numpy>=1.24.0",
    
    # Database
    "duckdb>=0.9.0",
    "psycopg2-binary>=2.9.7",  # For Supabase connection
    
    # dbt
    "dbt-core>=1.6.0",
    "dbt-duckdb>=1.6.0",
    
    # Utilities
    "python-dotenv>=1.0.0",
    "click>=8.1.0",  # For CLI commands
    "rich>=13.0.0",  # Beautiful console output
    "pydantic>=2.4.0",  # Data validation
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "black>=23.7.0",
    "ruff>=0.0.284",
    "mypy>=1.5.0",
    "jupyter>=1.0.0",  # For data exploration
]

[project.scripts]
# CLI commands for easy pipeline execution
pipeline-fetch = "data_pipeline.cli:fetch_data"
pipeline-transform = "data_pipeline.cli:run_transformations" 
pipeline-export = "data_pipeline.cli:export_to_supabase"
pipeline-run = "data_pipeline.cli:run_full_pipeline"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/data_pipeline"]

[tool.black]
line-length = 88
target-version = ['py310']

[tool.ruff]
line-length = 88
target-version = "py310"
select = ["E", "F", "I", "N", "W", "UP"]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]